highlighter: pygments
url: http://blog.matthewrathbone.com
name: Matthew Rathbone's website
version: 2.3
description: Blog posts and articles about Hadoop and other things
paginate: 5
exclude: ['ideas', 'drafts']
markdown: kramdown